name: Flutter Nightly Build

on:
  schedule:
    # schedule build every month frist day 12:00 am
    - cron: "00 12 1 * *"
  workflow_dispatch:

jobs:
  run-flutter-nightly-build:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: "nightly"
